#!/usr/bin/env node
'use strict';

const _ = require('lodash');
const fp = require('lodash/fp');
const inquirer = require('inquirer');

const questions2 = [ //noqa
  {
    type: 'list',
    name: 'theme',
    message: 'What do you want to do?',
    choices: [
      'Order a pizza',
      'Make a reservation',
      new inquirer.Separator(),
      'Ask for opening hours',
      {
        name: 'Contact support',
        disabled: 'Unavailable at this time'
      },
      'Talk to the receptionist'
    ]
  },
  {
    type: 'list',
    name: 'size',
    message: 'What size do you need?',
    choices: ['Jumbo', 'Large', 'Standard', 'Medium', 'Small', 'Micro'],
    filter: function (val) {
      return val.toLowerCase();
    }
  }
];

//const configs = [

//];

const mods = [
    require('./src/questions/dots.js').dots,
];

const questions = fp.map('question', mods);
const names = fp.map('name', mods);
const fns = fp.map('fn', mods);

inquirer
    .prompt(questions)
    .then(function (answers) {
        _.map(names, (name, index) => {
            return fns[index](answers[name]);
        });
    })
    .catch(console.error)
;
